version: '3.8'
services:
  mongo:
    image: mongo:6
    container_name: mongo-apprenant
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  apprenant-service:
    build: ./microcervices/apprenant-service
    container_name: apprenant-service
    restart: always
    ports:
      - "9200:9200"
    environment:
      - MONGO_URI=mongodb://mongo:27017/Microservice
      - BRIEF_SERVICE_URL=http://brief-service:3000
    depends_on:
      - mongo
    tty: true

volumes:
  mongo_data:
